# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
    ]
