# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20161103_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='num_commissions',
            field=models.IntegerField(default=0),
        ),
    ]
