# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_fandom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fandom',
            field=models.ManyToManyField(blank=True, null=True, to='commissions.Fandom'),
        ),
    ]
