# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_product_fandom'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='static/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=100),
        ),
    ]
