# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_auto_20161107_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
    ]
