# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_remove_productvariant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='description',
        ),
    ]
