# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_remove_productvariant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=29.99, max_digits=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='addon_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_1', to='commissions.ProductAddOn'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_2', to='commissions.ProductAddOn'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_3', to='commissions.ProductAddOn'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_4', to='commissions.ProductAddOn'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_5', to='commissions.ProductAddOn'),
        ),
        migrations.AddField(
            model_name='product',
            name='addon_6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_6', to='commissions.ProductAddOn'),
        ),
    ]
