# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_auto_20170113_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='request_detail_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
