# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_product_request_detail_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addon_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_6',
        ),
    ]
