# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
    ]
