# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161104_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
