# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161107_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True),
        ),
    ]
