# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
