# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20161116_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addon_1_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='addon_2_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='addon_3_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='addon_4_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='addon_5_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='addon_6_value',
            field=models.BooleanField(default=False),
        ),
    ]
