# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20161116_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
