# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstore',
            name='title',
        ),
        migrations.AlterField(
            model_name='userstore',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
