# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161106_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userstore',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstore',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
    ]
